### PR TITLE
v6.1 - .net6

### PR DESCRIPTION
**Pull request by andywilsonuk**
Hi Tony, I've found some time to put together the minimal .net 6 version, please can you review it?

There's a couple of fixes for broken tests and on separate commits I took the opportunity to remove implicit usings and fixed an error in the readme file.

### CODE REVIEW

**Comment by TonyValenti** [comment]
Awesome!  I'll review this later today. 
I'm sorry for not being able to tackle this myself. Been crazy busy with work!

**Comment by TonyValenti** [comment]
I'm going to merge this then review.

**Comment by TonyValenti** [comment]
Hi @andywilsonuk - This looks great.
Because Net48 is forever, I made a few small tweaks to enable it but they were basically just a few tweaks to the CSProjs.

**Comment by andywilsonuk** [comment]
Great. I'll look to get a package out tomorrow.

**Pull request merged**
